ASSYST - Lunch/WebUI/Models/EditProductViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class EditProductViewModel
    {
        public string Guid { get; set; }

        public string GuidShop { get; set; }

        [Required(ErrorMessage = "Veuillez entrer un nom pour le produit!")]
        [Display(Name = "Nom")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Veuillez entrer une description pour le produit!")]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Veuillez entrer un prix pour le produit!")]
        [Display(Name = "Prix")]
        public double Price { get; set; }

        [Required(ErrorMessage = "Veuillez préciser si le produit est autorisé!")]
        [Display(Name = "Actif")]
        public bool IsActive { get; set; }

        public IEnumerable<Shop> Shops { get; set; }
    }
}

ASSYST - Lunch/WebUI/Controllers/ProductController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository _repositoryProduct;
        private IShopRepository _repositoryShop;

        public ProductController(IProductRepository repoProductParam, IShopRepository repoShopParam)
        {
            _repositoryProduct = repoProductParam;
            _repositoryShop = repoShopParam;
        }

        public ViewResult ListProduct()
        {
            return View(_repositoryProduct.Products.Where(p => p.IsActive));
        }

        public ViewResult CreateProduct()
        {
            EditProductViewModel model = new EditProductViewModel
            {
                Shops = _repositoryShop.Shops.Where(p => p.IsActive)
            };
            return View("EditProduct", model);
        }

        public ViewResult EditProduct(string guid)
        {
            Product product = _repositoryProduct.Products.FirstOrDefault(p => p.Guid.Equals(guid));
            EditProductViewModel model = new EditProductViewModel
            {
                Guid = product.Guid,
                GuidShop = product.Shop?.Guid,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                IsActive = product.IsActive,
                Shops = _repositoryShop.Shops.Where(p => p.IsActive)
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult EditProduct(EditProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                Product product = new Product
                {
                    Guid = productViewModel.Guid,
                    Name = productViewModel.Name,
                    Description = productViewModel.Description,
                    Price = productViewModel.Price,
                    IsActive = productViewModel.IsActive
                };

                product.Shop = _repositoryShop.Shops.FirstOrDefault(s => s.Guid.Equals(productViewModel.GuidShop));
                _repositoryProduct.SaveProduct(product);
                return RedirectToAction("ListProduct");
            }
            else
            {
                return View(productViewModel);
            }
        }
    }
}

ASSYST - Lunch/WebUI/Controllers/ShopController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IShopRepository _repository;

        public ShopController(IShopRepository repoParam)
        {
            _repository = repoParam;
        }

        public ViewResult ListShop()
        {
            return View(_repository.Shops);
        }
        
        public ViewResult CreateShop()
        {
            return View("EditShop", new Shop());
        }

        public ViewResult EditShop(string guid)
        {
            Shop shop = _repository.Shops.FirstOrDefault(s => s.Guid.Equals(guid));
            return View(shop);
        }

        [HttpPost]
        public ActionResult EditShop(Shop shop)
        {
            if (ModelState.IsValid)
            {
                _repository.SaveShop(shop);
                TempData["Message"] = string.Format("\"{0}\" a été enregistré!", shop.Name);
                return RedirectToAction("ListShop");
            }
            else
            {
                return View(shop);
            }
        }
    }
}

ASSYST - Lunch/WebUI/Views/Product/EditProduct.cshtml
@using Domain.Entities
@model WebUI.Models.EditProductViewModel

@{ 
    List<SelectListItem> shopItems = new List<SelectListItem>();

    foreach(Shop shop in Model.Shops)
    {
        if (!string.IsNullOrEmpty(Model.GuidShop) && shop.Guid.Equals(Model.GuidShop))
        {
            shopItems.Add(new SelectListItem
                {
                    Text = shop.Name,
                    Value = shop.Guid,
                    Selected = true
                }
            );
        }
        else
        {
            shopItems.Add(new SelectListItem
                {
                    Text = shop.Name,
                    Value = shop.Guid
                }
            );
        }
    }
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Gestion Produit</h3>
    </div>
    @using (Html.BeginForm("EditProduct", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="card-body">
            @Html.HiddenFor(g => Model.Guid)

                @foreach (ModelMetadata productProperties in ViewData.ModelMetadata.Properties)
                {
                    if (!productProperties.PropertyName.Equals("IsActive") && !productProperties.PropertyName.Equals("Guid") 
                        && !productProperties.PropertyName.Equals("GuidShop") && !productProperties.PropertyName.Equals("Shops"))
                    {
                        <div class="form-group">
                            <label>@productProperties.DisplayName</label>
                            @Html.TextBox(productProperties.PropertyName, null, new { @class = "form-control" })
                        </div>
                    }

                    if (productProperties.PropertyName.Equals("IsActive"))
                    {
                        <div class="form-group">
                            <label>@productProperties.DisplayName</label>
                            @Html.CheckBox(productProperties.PropertyName, false)
                        </div>
                    }
                }

                @Html.DropDownListFor(p => Model.GuidShop, shopItems, "Choisissez un magasin")
        </div>
        <div class="card-footer">
            <input type="submit" value="Enregistrer" class="btn btn-primary" />
            @Html.ActionLink("Revenir à la liste", "ListProduct", null, new { @class = "btn btn-default"})
        </div>
    }
</div>

ASSYST - Lunch/WebUI/Views/Product/ListProduct.cshtml
@model IEnumerable<Domain.Entities.Product>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Produits</h3>
    </div>
    <div class="card-body">
        <table class="table table-striped table-bordered">
            <tr>
                <th class="text-center">Nom</th>
                <th class="text-center">description</th>
                <th class="text-center">Prix</th>
                <th class="text-center">Magasin</th>
                <th class="text-center">Actif</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach(var product in Model)
            {
                <tr>
                    <td class="text-center">@product.Name</td>
                    <td class="text-center"@product.Description></td>
                    <td class="text-center">@product.Price</td>
                    <td class="text-center">@product.Shop.Name</td>
                    <td class="text-center">
                        @if (product.IsActive)
                        {
                            <label>Actif</label>
                        }
                        else
                        {
                            <label>Inactif</label>
                        }
                    </td>
                    <td class="text-center">@Html.ActionLink("Modifier", "EditProduct", new { product.Guid })</td>
                </tr>    
            }
        </table>
    </div>
    <div class="card-footer">
        @Html.ActionLink("Ajouter un produit", "CreateProduct", null, new { @class = "btn btn-default"})
    </div>
</div>

ASSYST - Lunch/WebUI/Views/Shared/_Layout.cshtml

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <title>ASSYST - Lunch</title>
</head>
<body>
    <div class="container-fluid">
        @RenderBody()
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ASSYST - Lunch/WebUI/Views/Shop/EditShop.cshtml
@model Domain.Entities.Shop

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Gestion Magasin</h3>
    </div>
    
        @using (Html.BeginForm("EditShop", "Shop", FormMethod.Post, new { enctype = "multipart/form-data"}))
        {
            <div class="card-body">
                @Html.HiddenFor(s => s.Guid)
                @foreach (ModelMetadata property in ViewData.ModelMetadata.Properties)
                {
                    if (!property.PropertyName.Equals("IsActive") && !property.PropertyName.Equals("Guid") && !property.PropertyName.Equals("Products"))
                    {
                        <div class="form-group">
                            <label>@property.DisplayName</label>
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        </div>
                    }

                    if (property.PropertyName.Equals("IsActive"))
                    {
                        <div class="form-group">
                            <label>@property.DisplayName</label>
                            @Html.CheckBoxFor(s => s.IsActive)
                        </div>
                    }
                }
            </div>
            <div class="card-footer">
                <input type="submit" value="Enregistrer" class="btn btn-primary" />
                @Html.ActionLink("Revenir à la liste", "ListShop", null, new { @class = "btn btn-default"})
            </div>
        }   
</div>

ASSYST - Lunch/WebUI/Views/Shop/ListShop.cshtml
@model IEnumerable<Domain.Entities.Shop>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Magasins</h3>
    </div>
    <div class="card-body">
        <table class="table table-striped table-bordered">
            <tr>
                <th class="text-center">Nom</th>
                <th class="text-center">Adresse</th>
                <th class="text-center">Téléphone</th>
                <th class="text-center">Email</th>
                <th class="text-center">Commander avant</th>
                <th class="text-center">Actif</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach(var shop in Model)
            {
                <tr>
                    <td class="text-center">@shop.Name</td>
                    <td class="text-center">@string.Concat(shop.ZipCode, " ", shop.City, ", ", shop.Street, " ", shop.Number )</td>
                    <td class="text-center">@shop.Phone</td>
                    <td class="text-center">@shop.Mail</td>
                    <td class="text-center">@shop.OrderBefore</td>
                    <td class="text-center">
                        @if (shop.IsActive)
                        {
                            <label>Actif</label>
                        }
                        else
                        {
                            <label>Inactif</label>
                        }
                    </td>
                    <td class="text-center">@Html.ActionLink("Modifier", "EditShop", new { shop.Guid })</td>
                </tr>
            }
        </table>
    </div>
    <div class="card-footer">
        @Html.ActionLink("Ajouter un magasin", "CreateShop", null, new { @class = "btn btn-default"})
    </div>
</div>